AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.13
    Timeout: 30
    Environment:
      Variables:
        SECRET_NAME: life-admin/secrets
        REGION: ap-southeast-2

Resources:
  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: life-admin-dependencies
      ContentUri: layers/dependencies/
      CompatibleRuntimes:
        - python3.13
    Metadata:
      BuildMethod: python3.13

  SlackHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: functions.slack_handler.handler.lambda_handler
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - Statement:
            Effect: Allow
            Action: secretsmanager:GetSecretValue
            Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:life-admin/secrets-9MlbNy"
      Events:
        SlackEvent: # creates the API Gateway
          Type: Api
          Properties:
            Path: /slack
            Method: post

  RunPipelineFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: functions.run_pipeline.pipeline.lambda_handler
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - Statement:
            Effect: Allow
            Action: secretsmanager:GetSecretValue
            Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:life-admin/secrets-9MlbNy"
      Events:
        ScheduledRun: # creates the EventBridge rule
          Type: Schedule
          Properties:
            Schedule: cron(0 9 * * ? *)

Outputs:
  SlackHandlerUrl:
    Description: API Gateway URL for Slack interactions
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/slack"
